version: '3'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db/postgres"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:cached

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - db

